### ISSUE TITLE
Doesn't work in strict mode

### ISSUE THREAD

**Issue by romanesko** [rvagg/node-errno#17]
```
/Users/romka/Work/arduinoemu_openshift/node_modules/errno/custom.js:18
    Error.captureStackTrace(this, arguments.callee)
                                           ^

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Error.CustomError (/Users/romka/Work/arduinoemu_openshift/node_modules/errno/custom.js:18:44)
    at createError (/Users/romka/Work/arduinoemu_openshift/node_modules/errno/custom.js:42:43)
    at ce (/Users/romka/Work/arduinoemu_openshift/node_modules/errno/custom.js:48:12)
    at module.exports (/Users/romka/Work/arduinoemu_openshift/node_modules/errno/custom.js:52:25)
    at Object.<anonymous> (/Users/romka/Work/arduinoemu_openshift/node_modules/errno/errno.js:312:44)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
 at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by dcousens** [comment]
@rvagg any love for this?

**Comment by dcousens** [comment]
Related PRs:
https://github.com/rvagg/node-errno/pull/13
https://github.com/rvagg/node-errno/pull/18

**Comment by 311289189** [comment]
+1
